workflows:
  ios-workflow:
    name: ShortHop iOS
    environment:
      xcode: 16.3
      node: 20.19.4
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.hyperquency.shorthopapp
    scripts:
      - name: Install pods
        script: cd /Users/builder/clone/expo-ios-wrapper/ios && pod install
      - name: Build iOS
        script: |
          xcodebuild clean archive \
            -workspace /Users/builder/clone/expo-ios-wrapper/ios/ShortHop.xcworkspace \
            -scheme ShortHop \
            -archivePath /Users/builder/clone/build/ShortHop.xcarchive \
            -sdk iphoneos
    artifacts:
      - build/**/*.ipa
